# n8n with PostgreSQL and ngrok for public access
# n8n documentation: https://docs.n8n.io/hosting/installation/docker/

services:

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    ports:
      - 4040:4040
    command:
      - "http"
      - "n8n:5678" # 更改：直接指向 n8n 服務，更穩定
      - "--domain" # 新增：指定網域的參數
      - "joey-content-fawn.ngrok-free.app" # 改成你的固定網址
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    networks:
      - n8n_network

  postgres:
    image: postgres:15.3-alpine
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-n8n}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-n8npass8}
      POSTGRES_DB: ${POSTGRES_DB:-n8n}
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_network

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "${N8N_PORT:-5678}:5678"  # Port for local development and ngrok
    environment:
      # Database connection
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}
      - DB_POSTGRESDB_USER=${POSTGRES_USER:-n8n}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-n8npass8}

      # Authentication
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-adminpass}
      - N8N_RUNNERS_ENABLED=true

      # Host configuration
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - WEBHOOK_URL=${NGROK_PUBLIC_URL:-http://localhost:5678}

      # Execution settings
      - GENERIC_TIMEZONE=Asia/Taipei
      - TZ=Asia/Taipei

    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_network


  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

networks:
  n8n_network:
    name: n8n_network
    driver: bridge

volumes:
  ollama_data:
    name: ollama_data
  n8n_postgres_data:
    name: n8n_public_postgres_data  # Stores PostgreSQL database files
  n8n_data:
    name: n8n_public_data  # Stores n8n workflows, credentials, and binary data
